FROM tomcat:9-jdk8
LABEL author="divyak"
RUN wget https://referenceapplicationskhaja.s3.us-west-2.amazonaws.com/gameoflife.war
# COPY ./gameoflife.war /usr/local/tomcat/webapps/gameoflife.war
EXPOSE 8080